export const coinTypes = {
  FETCHING_COINS: "FETCHING_COINS",
  GET_CMC_COINS_SUCCESS: "GET_CMC_COINS_SUCCESS",
  GET_CMC_COINS_ERROR: "GET_CMC_COINS_ERROR",
  GET_USER_COINS_SUCCESS: "GET_USER_COINS_SUCCESS",
  GET_USER_COINS_ERROR: "GET_USER_COINS_ERROR",
  UPDATE_USER_COINS_SUCCESS: "UPDATE_USER_COINS_SUCCESS",
  UPDATE_USER_COINS_ERROR: "UPDATE_USER_COINS_ERROR"
};
