export const pageTypes = {
  DECREMENT_PAGE_SUCCESS: "DECREMENT_PAGE_SUCCESS",
  DECREMENT_PAGE_ERROR: "DECREMENT_PAGE_ERROR",
  INCREMENT_PAGE_SUCCESS: "INCREMENT_PAGE_SUCCESS",
  INCREMENT_PAGE_ERROR: "INCREMENT_PAGE_ERROR"
};
